# Generated by Django 4.0.1 on 2022-01-25 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affairs', '0002_students'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='full_name',
            new_name='name',
        ),
    ]
