# Generated by Django 4.0.1 on 2022-01-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affairs', '0003_rename_full_name_students_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intake',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=20)),
                ('sdate', models.DateField()),
                ('edate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
